### ISSUE TITLE
Покрыть тестами

### ISSUE THREAD

**Issue by tshemsedinov** [rediska-ua/game_tag#2]
Было бы очень желательно покрыть код тестами, тогда, гляди и структура кода приобретет лучший вид. Можно взять хоть `assert` из ноды или на выбор тестовый фреймворк, пересмотри мою лекцию по тестированию.

**Comment by sheiko-maksim** [comment]
Хорошо, понял, сделаю

**Comment by sheiko-maksim** [comment]
Добавил несколько тестов на входные данные в  отдельный файл.
